---
title: "Predicting Air Quality From Weather"
output: html_notebook
#rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Predicting Air Quality From Weather}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---

```{r setup}
# Set working directory to enjoy memoise cache
library(knitr)
knitr::opts_knit$set(root.dir = file.path(getwd(),'../'))
```

```{r message=FALSE, warning=FALSE}
library(creadb)
library(ggplot2)
library(dplyr)
library(gbm)
library(tidyr)
library(lubridate)
library(zoo)
getwd()
```

These are the high-level parameters:
```{r}
# Parameters
city=c('Delhi', 'Kolkata', 'Beijing')
poll <- creadb::PM25

# When to separate training data & prediction data
training_prediction_cut <- lubridate::as_date("2020-01-01")

# On what rolling average do we want to train the model
training_average_by='hour'
training_average_by_width=3

# On what rolling average do we want to plot results
plotting_average_by='day'
plotting_average_by_width=30
```

We first collect air quality measurements joined with weather observations from NOAA IDS dataset.
```{r}
# Get measurements (using the caching version aq_weather.M.collect)
meas_weather <- aq_weather.m.collect(city=city, poll=poll, average_by=training_average_by, weather_radius_km = 50)
meas_weather
```


### Exploring data
Let's see how many measurements we have:
```{r}
meas_weather %>% group_by(city, poll) %>% tally()
```

Let's look at a random month:
```{r warning=FALSE}
# Let's see the raw weather measurements we have on a random month (can be slow)
weather_vars <- vars(temp_c, slp_hp, wind_deg, wind_ms, sky_code, prec_1h_mm, prcp)
weather.plot <- tidyr::gather(meas_weather, "indicator", "value", -c(poll, city, date, country, value, location, location_id, name, sky_code)) %>% tidyr::drop_na(value)
ggplot(weather.plot, aes(x=date, y=value, colour=city)) +
  geom_point(size=0.4) + facet_wrap(~indicator, scales="free_y") +
  xlim(as.POSIXct("2019-08-01"), as.POSIXct("2019-08-31"))
```


Let's pick the models we want to apply. By default, there is a GBM and a RPART.
```{r}
meas_weather$wind_deg_factor = factor(meas_weather$wind_deg %/% 45)

formula <- value ~ temp_c + wind_deg_factor + wind_ms + slp_hp + rh_percent + sky_code
models <- aq_weather.default_models()
```


Run (fit & predict) models:
```{r message=FALSE, warning=FALSE}
result <- aq_weather.predict(meas_weather = meas_weather,
                             formula=formula,
                             training_prediction_cut = training_prediction_cut,
                             training_average_by = training_average_by,
                             training_average_by_width = training_average_by_width,
                             models = models)
result
```

Plotting results:
```{r warning=FALSE}
aq_weather.plot(result,
                plotting_average_by = plotting_average_by,
                plotting_average_by_width = plotting_average_by_width,
                training_prediction_cut = training_prediction_cut,
                subtitle=paste(paste(city, collapse=','),
                               paste("Training:",training_average_by_width, training_average_by),
                               paste(formula,collapse=''),
                               paste("Plotting:",plotting_average_by_width, plotting_average_by),sep="\n"),
                filename = paste0('export_',
                                 format(Sys.time(), "%Y-%m-%d_%H:%M"),'.pdf')
                )
```

```{r}
# Plotting residuals both on training and predicting
aq_weather.plot_residuals(result,
                          plotting_average_by = plotting_average_by,
                          plotting_average_by_width = plotting_average_by_width)
```

```{r}
# Plotting RMSE (computed only on training data)
ggplot(result, aes(x=model_name, y=rmse, fill=city)) + geom_bar(stat="identity",position=position_dodge())
```

```{r}


```
