---
title: "Querying and plotting air quality measurements with rcrea package"
#output: html_notebook
# output: rmarkdown::html_vignette
output:
  html_document:
    df_print: paged
vignette: >
  %\VignetteIndexEntry{Querying and plotting air quality measurements}
  %\VignetteEngine{knitr::rmarkdown}
  \usepackage[utf8]{inputenc}
---

## Installing package
```{r results="hide", eval=FALSE}
if(!require(remotes)){install.packages('remotes'); require(remotes)}
remotes::install_github("energyandcleanair/rcrea")
```
```{r results="hide", message=FALSE}
library(rcrea)
```


## Measurements
### Downloading measurements
Collecting measurements at the city level:
```{r message=FALSE, cache=TRUE}
meas_cities <- rcrea::measurements(city=c('Jaipur','Mumbai', 'Delhi'),
                                   source="cpcb",
                                   poll=c(rcrea::NO2, rcrea::PM25),
                                   date_from="2020-01-01")
meas_cities
```

Getting data at the station level (i.e. more granular than city).
```{r message=FALSE, cache=TRUE}
meas_stations <- rcrea::measurements(city=c('Beijing'),
                                     source="mee",
                                     aggregate_level = "station",
                                     poll=rcrea::NO2,
                                     date_from="2018-01-01")
meas_stations
```


### Plotting measurements


```{r message=FALSE, warning=FALSE, fig.width=10, out.width = "100%"}
rcrea::plot_recents(meas_raw=meas_cities,
                    subplot_by="poll",
                    color_by="location_name",
                    running_days = 30)
```
```{r message=FALSE, warning=FALSE, fig.width=10, out.width = "100%"}
rcrea::plot_recents(meas_raw=meas_stations,
                    subplot_by="location_id",
                    color_by="year",
                    running_days = 30)
```

Heatmap of standardized air quality level:
```{r message=FALSE, warning=FALSE, fig.width=10, out.width = "100%"}
rcrea::plot_measurements(meas_cities,
                         poll=PM25,
                         subplot_by='location_name',
                         type='heatmap',
                         average_by='day')
```

